# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Humioctl < Formula
  desc "Manage and Stream Logs to Humio"
  homepage "https://humio.com/"
  version "0.38.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humio/cli/releases/download/v0.38.0/humioctl_Darwin_x86_64.tar.gz"
      sha256 "d929ee0e17b03b48c6cfa02ed48e8acb906eebc9a6e4d20091c8df7f0dc2d1a0"

      def install
        bin.install "humioctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humio/cli/releases/download/v0.38.0/humioctl_Darwin_arm64.tar.gz"
      sha256 "e25d213c3845326237c1fdd59c81aebf3feb0946bd6c35fabedd9e08fc74c2ce"

      def install
        bin.install "humioctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humio/cli/releases/download/v0.38.0/humioctl_Linux_x86_64.tar.gz"
        sha256 "b138a8380dcdf439c0978cb8b8fac923d98da6295fb47674c23c129b04ea6e3c"

        def install
          bin.install "humioctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humio/cli/releases/download/v0.38.0/humioctl_Linux_arm64.tar.gz"
        sha256 "2097c7ab4cef5eeac5f9b211a242ed50064779458a4f4e377969d4b4fa8674e8"

        def install
          bin.install "humioctl"
        end
      end
    end
  end

  test do
    system "echo DONE"
  end
end
