# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Humioctl < Formula
  desc "Manage and Stream Logs to Humio"
  homepage "https://humio.com/"
  version "0.30.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humio/cli/releases/download/v0.30.2/humioctl_0.30.2_macOS_64-bit.tar.gz"
      sha256 "30cc0433bca8b6a9b6614b67b9e310d1305e5f5f3ef0edda3eac8ad3935aa0af"

      def install
        bin.install "humioctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humio/cli/releases/download/v0.30.2/humioctl_0.30.2_macOS_arm64.tar.gz"
      sha256 "9c77a5206a80e150e506e365bcc3fdd07554e22625d17327faf289fd850bf805"

      def install
        bin.install "humioctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/humio/cli/releases/download/v0.30.2/humioctl_0.30.2_Linux_64-bit.tar.gz"
      sha256 "04f8a3eb34d2739d0e27553a6d08465cb40d4929c63756fc8f6afb530a29cbed"

      def install
        bin.install "humioctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/humio/cli/releases/download/v0.30.2/humioctl_0.30.2_Linux_arm64.tar.gz"
      sha256 "a954c7d7d85295b782a3e7c521ec94a44d7bc87ab2f9f52d08cd5d139da159d7"

      def install
        bin.install "humioctl"
      end
    end
  end

  test do
    system "echo DONE"
  end
end
